# Generated by Django 4.1.5 on 2023-01-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_catname_categories_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
